### ISSUE TITLE
有人遇到过这个问题？32-bit application should be automated using 32-bit Python (you use 64-bit Python)

### ISSUE THREAD

**Issue by jasonLaw1015** [Delta-F/DeltaTrader#6]
E:\ProgramData\miniconda3\lib\site-packages\pywinauto\application.py:1062: UserWarning: 32-bit application should be automated using 32-bit Python (you use 64-bit Python)
  warnings.warn(
Traceback (most recent call last):
  File "D:\develop\python\DeltaTrader\trader\etrader.py", line 19, in <module>
    user.connect(r'D:\同花顺软件\同花顺\xiadan.exe')  # 类似 r'C:\htzqzyb2\xiadan.exe'
  File "E:\ProgramData\miniconda3\lib\site-packages\easytrader\clienttrader.py", line 118, in connect
    self._main = self._app.top_window()
  File "E:\ProgramData\miniconda3\lib\site-packages\pywinauto\application.py", line 1133, in top_window
    raise RuntimeError("No windows for that process could be found")
RuntimeError: No windows for that process could be found

Process finished with exit code 1

**Comment by jasonLaw1015** [comment]
是安装个python32位解决还是找一个同花顺64位的软件呢？

我32位的python3.10.0 32位安装easytrader又报以下错：
Building wheels for collected packages: pillow
  Building wheel for pillow (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: 'E:\ProgramData\miniconda3\envs\py32\python.exe' 'E:\ProgramData\miniconda3\envs\py32\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' build_wheel 'C:\Users\ADMINI~1\AppData\Local\Temp\tmpke3dyivd'
       cwd: C:\Users\Administrator\AppData\Local\Temp\pip-install-kisc10ee\pillow_03fc5efb70674a9e9a885dc94c23e8ed
  Complete output (199 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win32-cpython-310
  creating build\lib.win32-cpython-310\PIL
  copying src\PIL\BdfFontFile.py -> build\lib.win32-cpython-310\PIL
  copying src\PIL\BlpImagePlugin.py -> build\lib.win32-cpython-310\PIL
  copying src\PIL\BmpImagePlugin.py -> build\lib.win32-cpython-310\PIL
  copying src\PIL\BufrStubImagePlugin.py -> build\lib.win32-cpython-310\PIL
  copying src\PIL\ContainerIO.py -> build\lib.win32-cpython-310\PIL
  copying src\PIL\CurImagePlugin.py -> build\lib.win32-cpython-310\PIL
  copying src\PIL\DcxImagePlugin.py -> build\lib.win32-cpython-310\PIL
  copying src\PIL\DdsImagePlugin.py -> build\lib.win32-cpython-310\PIL
  copying src\PIL\EpsImagePlugin.py -> build\lib.win32-cpython-310\PIL
  copying src\PIL\ExifTags.py -> build\lib.win32-cpython-310\PIL
  copying src\PIL\features.py -> build\lib.win32-cpython-310\PIL
  copying src\PIL\FitsImagePlugin.py -> build\lib.win32-cpython-310\PIL
  copying src\PIL\FliImagePlugin.py -> build\lib.win32-cpython-310\PIL
  copying src\PIL\FontFile.py -> build\lib.win32-cpython-310\PIL
  copying src\PIL\FpxImagePlugin.py -> build\lib.win32-cpython-310\PIL
  copying src\PIL\FtexImagePlugin.py -> build\lib.win32-cpython-310\PIL
  copying src\PIL\GbrImagePlugin.py -> build\lib.win32-cpython-310\PIL
  copying src\PIL\GdImageFile.py -> build\lib.win32-cpython-310\PIL
  copying src\PIL\GifImagePlugin.py -> build\lib.win32-cpython-310\PIL
  copying src\PIL\GimpGradientFile.py -> build\lib.win32-cpython-310\PIL
  copying src\PIL\GimpPaletteFile.py -> build\lib.win32-cpython-310\PIL
  copying src\PIL\GribStubImagePlugin.py -> build\lib.win32-cpython-310\PIL
  copying src\PIL\Hdf5StubImagePlugin.py -> build\lib.win32-cpython-310\PIL
  copying src\PIL\IcnsImagePlugin.py -> build\lib.win32-cpython-310\PIL
  copying src\PIL\IcoImagePlugin.py -> build\lib.win32-cpython-310\PIL
  copying src\PIL\Image.py -> build\lib.win32-cpython-310\PIL
  copying src\PIL\ImageChops.py -> build\lib.win32-cpython-310\PIL
  copying src\PIL\ImageCms.py -> build\lib.win32-cpython-310\PIL
  copying src\PIL\ImageColor.py -> build\lib.win32-cpython-310\PIL
  copying src\PIL\ImageDraw.py -> build\lib.win32-cpython-310\PIL
  copying src\PIL\ImageDraw2.py -> build\lib.win32-cpython-310\PIL
  copying src\PIL\ImageEnhance.py -> build\lib.win32-cpython-310\PIL
  copying src\PIL\ImageFile.py -> build\lib.win32-cpython-310\PIL
  copying src\PIL\ImageFilter.py -> build\lib.win32-cpython-310\PIL
  copying src\PIL\ImageFont.py -> build\lib.win32-cpython-310\PIL
  copying src\PIL\ImageGrab.py -> build\lib.win32-cpython-310\PIL
  copying src\PIL\ImageMath.py -> build\lib.win32-cpython-310\PIL
  copying src\PIL\ImageMode.py -> build\lib.win32-cpython-310\PIL
  copying src\PIL\ImageMorph.py -> build\lib.win32-cpython-310\PIL
  copying src\PIL\ImageOps.py -> build\lib.win32-cpython-310\PIL
  copying src\PIL\ImagePalette.py -> build\lib.win32-cpython-310\PIL
  copying src\PIL\ImagePath.py -> build\lib.win32-cpython-310\PIL
  copying src\PIL\ImageQt.py -> build\lib.win32-cpython-310\PIL
  copying src\PIL\ImageSequence.py -> build\lib.win32-cpython-310\PIL
  copying src\PIL\ImageShow.py -> build\lib.win32-cpython-310\PIL
  copying src\PIL\ImageStat.py -> build\lib.win32-cpython-310\PIL
  copying src\PIL\ImageTk.py -> build\lib.win32-cpython-310\PIL
  copying src\PIL\ImageTransform.py -> build\lib.win32-cpython-310\PIL
  copying src\PIL\ImageWin.py -> build\lib.win32-cpython-310\PIL
  copying src\PIL\ImImagePlugin.py -> build\lib.win32-cpython-310\PIL
  copying src\PIL\ImtImagePlugin.py -> build\lib.win32-cpython-310\PIL
  copying src\PIL\IptcImagePlugin.py -> build\lib.win32-cpython-310\PIL
  copying src\PIL\Jpeg2KImagePlugin.py -> build\lib.win32-cpython-310\PIL
  copying src\PIL\JpegImagePlugin.py -> build\lib.win32-cpython-310\PIL
  copying src\PIL\JpegPresets.py -> build\lib.win32-cpython-310\PIL
  copying src\PIL\McIdasImagePlugin.py -> build\lib.win32-cpython-310\PIL
  copying src\PIL\MicImagePlugin.py -> build\lib.win32-cpython-310\PIL
  copying src\PIL\MpegImagePlugin.py -> build\lib.win32-cpython-310\PIL
  copying src\PIL\MpoImagePlugin.py -> build\lib.win32-cpython-310\PIL
  copying src\PIL\MspImagePlugin.py -> build\lib.win32-cpython-310\PIL
  copying src\PIL\PaletteFile.py -> build\lib.win32-cpython-310\PIL
  copying src\PIL\PalmImagePlugin.py -> build\lib.win32-cpython-310\PIL
  copying src\PIL\PcdImagePlugin.py -> build\lib.win32-cpython-310\PIL
  copying src\PIL\PcfFontFile.py -> build\lib.win32-cpython-310\PIL
  copying src\PIL\PcxImagePlugin.py -> build\lib.win32-cpython-310\PIL
  copying src\PIL\PdfImagePlugin.py -> build\lib.win32-cpython-310\PIL
  copying src\PIL\PdfParser.py -> build\lib.win32-cpython-310\PIL
  copying src\PIL\PixarImagePlugin.py -> build\lib.win32-cpython-310\PIL
  copying src\PIL\PngImagePlugin.py -> build\lib.win32-cpython-310\PIL
